[devshell]
packages = [
  "alejandra",
  "cargo-edit",
  "cargo-make",
  "cargo-watch",
  "dprint",
  "openssl",
  "pkgconfig",
  "rust-analyzer",
  "wasm-pack",
  "nodejs-18_x",
  "nodePackages.pnpm",
]

[[commands]]
package = "treefmt"
category = "formatter"
