[devshell]
packages = [
  "alejandra",
  "cargo-edit",
  "cargo-make",
  "cargo-watch",
  "dprint",
  "openssl",
  "pkgconfig",
  "rust-analyzer",
  "wasm-pack",
]

[[commands]]
package = "treefmt"
category = "formatter"
