[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = [
  "*.json",
  "*.code-workspace",
  "*.toml",
  "*.md",
]

[formatter.rustfmt]
command = "rustfmt"
includes = [
  "*.rs",
]
